# Generated by Django 3.2.8 on 2021-10-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=250)),
                ('unit', models.CharField(max_length=250)),
                ('bulding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.building')),
            ],
        ),
        migrations.CreateModel(
            name='HalfHourData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.CharField(max_length=250)),
                ('reading_date_time', models.DateTimeField()),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meterdata')),
            ],
        ),
    ]
