# Generated by Django 3.2.8 on 2021-10-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halfhourdata',
            name='consumption',
            field=models.DecimalField(decimal_places=5, max_digits=9),
        ),
    ]
