# Generated by Django 3.2.8 on 2021-10-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_halfhourdata_consumption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='halfhourdata',
            old_name='meter_id',
            new_name='meter',
        ),
        migrations.RenameField(
            model_name='halfhourdata',
            old_name='reading_date_time',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='meterdata',
            old_name='bulding_id',
            new_name='building',
        ),
    ]
